<?php

namespace JoliCode\MediaBundle\Bridge\EasyAdmin\Routing;

use EasyCorp\Bundle\EasyAdminBundle\Config\Option\EA;
use JoliCode\MediaBundle\Bridge\EasyAdmin\Controller\MediaAdminController;
use Symfony\Component\Config\Loader\Loader;
use Symfony\Component\Config\Loader\LoaderInterface;
use Symfony\Component\Config\Loader\LoaderResolverInterface;
use Symfony\Component\Routing\RouteCollection;

/**
 * Decorates the EasyAdmin route loader to apply the configured path prefix to the
 * media library routes.
 *
 * The routes of the media library are generated by EasyAdmin from the #[AdminRoute]
 * attributes of the MediaAdminController. PHP attributes only hold static values, so
 * the controller declares a placeholder prefix, which is substituted here with the
 * "joli_media_easy_admin.path_prefix" configuration value.
 */
final class MediaAdminRouteLoader extends Loader
{
    public function __construct(
        private readonly LoaderInterface $decorated,
        private readonly string $pathPrefix,
    ) {
        parent::__construct();
    }

    #[\Override]
    public function supports(mixed $resource, ?string $type = null): bool
    {
        return $this->decorated->supports($resource, $type);
    }

    #[\Override]
    public function load(mixed $resource, ?string $type = null): RouteCollection
    {
        $routes = $this->decorated->load($resource, $type);

        if (!$routes instanceof RouteCollection) {
            throw new \LogicException(\sprintf('The decorated "%s" route loader was expected to return a "%s".', $this->decorated::class, RouteCollection::class));
        }

        foreach ($routes as $route) {
            if (MediaAdminController::class !== $route->getDefault(EA::CRUD_CONTROLLER_FQCN)) {
                continue;
            }

            $route->setPath(str_replace(
                '/' . MediaAdminController::PATH_PREFIX_PLACEHOLDER,
                '/' . $this->pathPrefix,
                $route->getPath(),
            ));
        }

        return $routes;
    }

    #[\Override]
    public function setResolver(LoaderResolverInterface $resolver): void
    {
        parent::setResolver($resolver);
        $this->decorated->setResolver($resolver);
    }
}
