<?php

use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

return static function (RoutingConfigurator $routes): void {
    $routes->import('../src/Controller/', 'attribute');
    $routes->import('.', 'easyadmin.routes');
    $routes->import('@JoliMediaBundle/config/routes.php');
    // the EasyAdmin media library routes are generated by EasyAdmin itself, from the
    // #[AdminRoute] attributes of the MediaAdminController
    $routes->import('@JoliMediaSyliusBundle/src/Admin/Controller/')->prefix('/sylius-admin/media');
    $routes->import('@SyliusAdminUiBundle/config/routes.php')->prefix('/sylius-admin');
    $routes->import('sylius.symfony.routing.loader.resource', 'service');
};
