<?php

namespace JoliCode\MediaBundle\Bridge\EasyAdmin\Router;

use EasyCorp\Bundle\EasyAdminBundle\Contracts\Provider\AdminContextProviderInterface;
use EasyCorp\Bundle\EasyAdminBundle\Contracts\Router\AdminRouteGeneratorInterface;
use EasyCorp\Bundle\EasyAdminBundle\Router\AdminUrlGeneratorInterface;
use JoliCode\MediaBundle\Bridge\EasyAdmin\Controller\MediaAdminController;

/**
 * Resolves the Symfony route name of every media library action, and generates
 * the matching admin URLs.
 *
 * The media library actions carry both #[AdminRoute] and #[Route] attributes:
 *
 * - when the application uses EasyAdmin pretty URLs, EasyAdmin generates the routes
 *   itself from the #[AdminRoute] attributes. This is what makes the media library
 *   reachable through pretty URLs such as "/admin/media/explore/photos", instead of
 *   "/admin?routeName=joli_media_easy_admin_explore&routeParams[key]=photos". These
 *   route names are prefixed with the route name of the dashboard they belong to, so
 *   they can only be resolved at runtime;
 * - otherwise (EasyAdmin 4.x applications which did not opt into pretty URLs), the
 *   routes declared with the plain #[Route] attributes are used, and their static
 *   "joli_media_easy_admin_*" names are returned instead.
 */
readonly class MediaAdminRouter
{
    /**
     * Maps the media library action names to the name of the route declared with a
     * plain #[Route] attribute, used when EasyAdmin does not generate the routes.
     *
     * @var array<string, string>
     */
    private const LEGACY_ROUTE_NAMES = [
        'choose' => 'joli_media_easy_admin_choose',
        'chooseDirectory' => 'joli_media_easy_admin_choose_directory',
        'createDirectory' => 'joli_media_easy_admin_create_directory',
        'delete' => 'joli_media_easy_admin_delete',
        'deleteDirectory' => 'joli_media_easy_admin_delete_directory',
        'explore' => 'joli_media_easy_admin_explore',
        'move' => 'joli_media_easy_admin_move',
        'regenerateVariation' => 'joli_media_easy_admin_regenerate_variation',
        'renameDirectory' => 'joli_media_easy_admin_rename_directory',
        'show' => 'joli_media_easy_admin_show',
        'upload' => 'joli_media_easy_admin_upload',
    ];

    public function __construct(
        private AdminUrlGeneratorInterface $adminUrlGenerator,
        private AdminRouteGeneratorInterface $adminRouteGenerator,
        private AdminContextProviderInterface $adminContextProvider,
    ) {
    }

    /**
     * @param string $action the name of a MediaAdminController action, eg. "explore" or "chooseDirectory"
     */
    public function getRouteName(string $action): string
    {
        if (!isset(self::LEGACY_ROUTE_NAMES[$action])) {
            throw new \InvalidArgumentException(\sprintf('"%s" is not a media library action. Expected one of: "%s".', $action, implode('", "', array_keys(self::LEGACY_ROUTE_NAMES))));
        }

        $dashboardFqcn = $this->adminContextProvider->getContext()?->getDashboardControllerFqcn();

        if (null !== $dashboardFqcn) {
            $routeName = $this->adminRouteGenerator->findRouteName($dashboardFqcn, MediaAdminController::class, $action);

            if (null !== $routeName) {
                return $routeName;
            }
        }

        return self::LEGACY_ROUTE_NAMES[$action];
    }

    /**
     * @param string               $action          the name of a MediaAdminController action, eg. "explore" or "chooseDirectory"
     * @param array<string, mixed> $routeParameters parameters of the media library route
     * @param array<string, mixed> $queryParameters parameters which are not part of the route, eg. "page" or "view_mode"
     */
    public function generateUrl(string $action, array $routeParameters = [], array $queryParameters = []): string
    {
        $routeName = $this->getRouteName($action);

        if ($routeName !== self::LEGACY_ROUTE_NAMES[$action]) {
            // the URL is generated from the media library route itself, so every
            // parameter which is not part of its path lands in the query string
            return $this->adminUrlGenerator
                ->setRoute($routeName, array_merge($routeParameters, $queryParameters))
                ->generateUrl()
            ;
        }

        // the URL points at the dashboard route, which carries the media library route
        // name and its parameters: the extra parameters must stay top-level ones
        $adminUrlGenerator = $this->adminUrlGenerator->setRoute($routeName, $routeParameters);

        foreach ($queryParameters as $name => $value) {
            $adminUrlGenerator = $adminUrlGenerator->set($name, $value);
        }

        return $adminUrlGenerator->generateUrl();
    }

    /**
     * Whether the media library routes are generated by EasyAdmin, ie. whether the
     * media library is browsed through pretty URLs.
     */
    public function usesPrettyUrls(): bool
    {
        return self::LEGACY_ROUTE_NAMES['explore'] !== $this->getRouteName('explore');
    }
}
